# Generated by Django 4.2.7 on 2024-03-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='время последней попытки')),
                ('attempt_status', models.CharField(blank=True, choices=[('Успешно', 'Success'), ('Неуспешно', 'Failed')], max_length=15, null=True, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, max_length=255, null=True, verbose_name='ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('attempt_status',),
            },
        ),
        migrations.RenameModel(
            old_name='MailingMessage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='MailingList',
            new_name='Mailing',
        ),
        migrations.DeleteModel(
            name='MailingLog',
        ),
        migrations.AddField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка'),
        ),
    ]
