# Generated by Django 4.2.7 on 2024-03-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('mailing', '0002_log_rename_mailingmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start', 'end'), 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('owner', 'is_published'), 'permissions': [('can_cancel_mailing', 'Может отменять публикацию рассылки')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='mail_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='mail_period',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='mail_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='mail_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='recipient',
        ),
        migrations.AddField(
            model_name='message',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликована'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', related_query_name='mail', to=settings.AUTH_USER_MODEL, verbose_name='автор рассылки'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ManyToManyField(related_name='clients', to='clients.client', verbose_name='клиенты'),
        ),
    ]
