# Generated by Django 4.2.7 on 2024-03-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_next_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующая отправка'),
        ),
    ]
